//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//


package com.ap.menabev.soap.journalcreatebinding;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryCashDiscountTerms complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryCashDiscountTerms"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DueCalculationBaseDate" type="{http://sap.com/xi/SAPSCORE/SFIN}Date"/&gt;
 *         &lt;element name="CashDiscount1Days" type="{http://sap.com/xi/SAPSCORE/SFIN}DAY_Duration" minOccurs="0"/&gt;
 *         &lt;element name="CashDiscount1Percent" type="{http://sap.com/xi/SAPSCORE/SFIN}Percent" minOccurs="0"/&gt;
 *         &lt;element name="CashDiscount2Days" type="{http://sap.com/xi/SAPSCORE/SFIN}DAY_Duration" minOccurs="0"/&gt;
 *         &lt;element name="CashDiscount2Percent" type="{http://sap.com/xi/SAPSCORE/SFIN}Percent" minOccurs="0"/&gt;
 *         &lt;element name="NetPaymentDays" type="{http://sap.com/xi/SAPSCORE/SFIN}DAY_Duration"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryCashDiscountTerms", propOrder = {
    "dueCalculationBaseDate",
    "cashDiscount1Days",
    "cashDiscount1Percent",
    "cashDiscount2Days",
    "cashDiscount2Percent",
    "netPaymentDays"
})
public class JournalEntryCreateRequestJournalEntryCashDiscountTerms {

    @XmlElement(name = "DueCalculationBaseDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueCalculationBaseDate;
    @XmlElement(name = "CashDiscount1Days")
    protected Duration cashDiscount1Days;
    @XmlElement(name = "CashDiscount1Percent")
    protected BigDecimal cashDiscount1Percent;
    @XmlElement(name = "CashDiscount2Days")
    protected Duration cashDiscount2Days;
    @XmlElement(name = "CashDiscount2Percent")
    protected BigDecimal cashDiscount2Percent;
    @XmlElement(name = "NetPaymentDays", required = true)
    protected Duration netPaymentDays;

    /**
     * Gets the value of the dueCalculationBaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueCalculationBaseDate() {
        return dueCalculationBaseDate;
    }

    /**
     * Sets the value of the dueCalculationBaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueCalculationBaseDate(XMLGregorianCalendar value) {
        this.dueCalculationBaseDate = value;
    }

    /**
     * Gets the value of the cashDiscount1Days property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getCashDiscount1Days() {
        return cashDiscount1Days;
    }

    /**
     * Sets the value of the cashDiscount1Days property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setCashDiscount1Days(Duration value) {
        this.cashDiscount1Days = value;
    }

    /**
     * Gets the value of the cashDiscount1Percent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashDiscount1Percent() {
        return cashDiscount1Percent;
    }

    /**
     * Sets the value of the cashDiscount1Percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashDiscount1Percent(BigDecimal value) {
        this.cashDiscount1Percent = value;
    }

    /**
     * Gets the value of the cashDiscount2Days property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getCashDiscount2Days() {
        return cashDiscount2Days;
    }

    /**
     * Sets the value of the cashDiscount2Days property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setCashDiscount2Days(Duration value) {
        this.cashDiscount2Days = value;
    }

    /**
     * Gets the value of the cashDiscount2Percent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashDiscount2Percent() {
        return cashDiscount2Percent;
    }

    /**
     * Sets the value of the cashDiscount2Percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashDiscount2Percent(BigDecimal value) {
        this.cashDiscount2Percent = value;
    }

    /**
     * Gets the value of the netPaymentDays property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getNetPaymentDays() {
        return netPaymentDays;
    }

    /**
     * Sets the value of the netPaymentDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setNetPaymentDays(Duration value) {
        this.netPaymentDays = value;
    }

}
