//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//


package com.ap.menabev.soap.journalcreatebinding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryWithholdingTaxItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryWithholdingTaxItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReferenceDocumentItem" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessTransactionDocumentItemID" minOccurs="0"/&gt;
 *         &lt;element name="WithholdingTaxType" type="{http://sap.com/xi/SAPSCORE/SFIN}WithholdingTaxType"/&gt;
 *         &lt;element name="WithholdingTaxCode" type="{http://sap.com/xi/SAPSCORE/SFIN}WithholdingTaxCode"/&gt;
 *         &lt;element name="AmountInTransactionCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="AmountInCompanyCodeCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="AmountInGroupCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="TaxBaseAmountInTransCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount"/&gt;
 *         &lt;element name="TaxBaseAmountInCoCodeCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="TaxBaseAmountInGroupCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="TaxIsToBeCalculated" type="{http://sap.com/xi/SAPSCORE/SFIN}Indicator" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryWithholdingTaxItem", propOrder = {
    "referenceDocumentItem",
    "withholdingTaxType",
    "withholdingTaxCode",
    "amountInTransactionCurrency",
    "amountInCompanyCodeCurrency",
    "amountInGroupCurrency",
    "taxBaseAmountInTransCrcy",
    "taxBaseAmountInCoCodeCrcy",
    "taxBaseAmountInGroupCrcy",
    "taxIsToBeCalculated"
})
public class JournalEntryCreateRequestJournalEntryWithholdingTaxItem {

    @XmlElement(name = "ReferenceDocumentItem")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String referenceDocumentItem;
    @XmlElement(name = "WithholdingTaxType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String withholdingTaxType;
    @XmlElement(name = "WithholdingTaxCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String withholdingTaxCode;
    @XmlElement(name = "AmountInTransactionCurrency")
    protected Amount amountInTransactionCurrency;
    @XmlElement(name = "AmountInCompanyCodeCurrency")
    protected Amount amountInCompanyCodeCurrency;
    @XmlElement(name = "AmountInGroupCurrency")
    protected Amount amountInGroupCurrency;
    @XmlElement(name = "TaxBaseAmountInTransCrcy", required = true)
    protected Amount taxBaseAmountInTransCrcy;
    @XmlElement(name = "TaxBaseAmountInCoCodeCrcy")
    protected Amount taxBaseAmountInCoCodeCrcy;
    @XmlElement(name = "TaxBaseAmountInGroupCrcy")
    protected Amount taxBaseAmountInGroupCrcy;
    @XmlElement(name = "TaxIsToBeCalculated")
    protected Boolean taxIsToBeCalculated;

    /**
     * Gets the value of the referenceDocumentItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceDocumentItem() {
        return referenceDocumentItem;
    }

    /**
     * Sets the value of the referenceDocumentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceDocumentItem(String value) {
        this.referenceDocumentItem = value;
    }

    /**
     * Gets the value of the withholdingTaxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithholdingTaxType() {
        return withholdingTaxType;
    }

    /**
     * Sets the value of the withholdingTaxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithholdingTaxType(String value) {
        this.withholdingTaxType = value;
    }

    /**
     * Gets the value of the withholdingTaxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithholdingTaxCode() {
        return withholdingTaxCode;
    }

    /**
     * Sets the value of the withholdingTaxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithholdingTaxCode(String value) {
        this.withholdingTaxCode = value;
    }

    /**
     * Gets the value of the amountInTransactionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmountInTransactionCurrency() {
        return amountInTransactionCurrency;
    }

    /**
     * Sets the value of the amountInTransactionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmountInTransactionCurrency(Amount value) {
        this.amountInTransactionCurrency = value;
    }

    /**
     * Gets the value of the amountInCompanyCodeCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmountInCompanyCodeCurrency() {
        return amountInCompanyCodeCurrency;
    }

    /**
     * Sets the value of the amountInCompanyCodeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmountInCompanyCodeCurrency(Amount value) {
        this.amountInCompanyCodeCurrency = value;
    }

    /**
     * Gets the value of the amountInGroupCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmountInGroupCurrency() {
        return amountInGroupCurrency;
    }

    /**
     * Sets the value of the amountInGroupCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmountInGroupCurrency(Amount value) {
        this.amountInGroupCurrency = value;
    }

    /**
     * Gets the value of the taxBaseAmountInTransCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxBaseAmountInTransCrcy() {
        return taxBaseAmountInTransCrcy;
    }

    /**
     * Sets the value of the taxBaseAmountInTransCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxBaseAmountInTransCrcy(Amount value) {
        this.taxBaseAmountInTransCrcy = value;
    }

    /**
     * Gets the value of the taxBaseAmountInCoCodeCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxBaseAmountInCoCodeCrcy() {
        return taxBaseAmountInCoCodeCrcy;
    }

    /**
     * Sets the value of the taxBaseAmountInCoCodeCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxBaseAmountInCoCodeCrcy(Amount value) {
        this.taxBaseAmountInCoCodeCrcy = value;
    }

    /**
     * Gets the value of the taxBaseAmountInGroupCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxBaseAmountInGroupCrcy() {
        return taxBaseAmountInGroupCrcy;
    }

    /**
     * Sets the value of the taxBaseAmountInGroupCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxBaseAmountInGroupCrcy(Amount value) {
        this.taxBaseAmountInGroupCrcy = value;
    }

    /**
     * Gets the value of the taxIsToBeCalculated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxIsToBeCalculated() {
        return taxIsToBeCalculated;
    }

    /**
     * Sets the value of the taxIsToBeCalculated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxIsToBeCalculated(Boolean value) {
        this.taxIsToBeCalculated = value;
    }

}
