//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//


package com.ap.menabev.soap.journalcreatebinding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JournalEntryCreateConfirmationMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateConfirmationMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageHeader" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessDocumentMessageHeader"/&gt;
 *         &lt;element name="JournalEntryCreateConfirmation" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateConfirmationJournalEntry" minOccurs="0"/&gt;
 *         &lt;element name="Log" type="{http://sap.com/xi/SAPSCORE/SFIN}Log" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateConfirmationMessage", propOrder = {
    "messageHeader",
    "journalEntryCreateConfirmation",
    "log"
})
public class JournalEntryCreateConfirmationMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected BusinessDocumentMessageHeader messageHeader;
    @XmlElement(name = "JournalEntryCreateConfirmation")
    protected JournalEntryCreateConfirmationJournalEntry journalEntryCreateConfirmation;
    @XmlElement(name = "Log")
    protected Log log;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessDocumentMessageHeader }
     *     
     */
    public BusinessDocumentMessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessDocumentMessageHeader }
     *     
     */
    public void setMessageHeader(BusinessDocumentMessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the journalEntryCreateConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link JournalEntryCreateConfirmationJournalEntry }
     *     
     */
    public JournalEntryCreateConfirmationJournalEntry getJournalEntryCreateConfirmation() {
        return journalEntryCreateConfirmation;
    }

    /**
     * Sets the value of the journalEntryCreateConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalEntryCreateConfirmationJournalEntry }
     *     
     */
    public void setJournalEntryCreateConfirmation(JournalEntryCreateConfirmationJournalEntry value) {
        this.journalEntryCreateConfirmation = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

}
