//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//


package com.ap.menabev.soap.journalcreatebinding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Customer" type="{http://sap.com/xi/SAPSCORE/SFIN}Customer" minOccurs="0"/&gt;
 *         &lt;element name="CustomerGroup" type="{http://sap.com/xi/SAPSCORE/SFIN}CustomerGroupCode" minOccurs="0"/&gt;
 *         &lt;element name="CustomerIndustry" type="{http://sap.com/xi/SAPSCORE/SFIN}IndustrialSectorCode" minOccurs="0"/&gt;
 *         &lt;element name="CustomerCountry" type="{http://sap.com/xi/SAPSCORE/SFIN}CountryCode" minOccurs="0"/&gt;
 *         &lt;element name="SalesDistrict" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesDistrict" minOccurs="0"/&gt;
 *         &lt;element name="SoldMaterial" type="{http://sap.com/xi/SAPSCORE/SFIN}Material" minOccurs="0"/&gt;
 *         &lt;element name="SoldMaterialGroup" type="{http://sap.com/xi/SAPSCORE/SFIN}MaterialGroup" minOccurs="0"/&gt;
 *         &lt;element name="SalesOrganization" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesOrganization" minOccurs="0"/&gt;
 *         &lt;element name="DistributionChannel" type="{http://sap.com/xi/SAPSCORE/SFIN}DistributionChannelCode" minOccurs="0"/&gt;
 *         &lt;element name="Division" type="{http://sap.com/xi/SAPSCORE/SFIN}DivisionCode" minOccurs="0"/&gt;
 *         &lt;element name="BillToParty" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessPartnerInternalID" minOccurs="0"/&gt;
 *         &lt;element name="ShipToParty" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessPartnerInternalID" minOccurs="0"/&gt;
 *         &lt;element name="PersonnelNumber" type="{http://sap.com/xi/SAPSCORE/SFIN}PersonnelNumber_GFN" minOccurs="0"/&gt;
 *         &lt;element name="WBSElement" type="{http://sap.com/xi/SAPSCORE/SFIN}WBSElement" minOccurs="0"/&gt;
 *         &lt;element name="FunctionalArea" type="{http://sap.com/xi/SAPSCORE/SFIN}FunctionalArea_GFN" minOccurs="0"/&gt;
 *         &lt;element name="ServiceDocType" type="{http://sap.com/xi/SAPSCORE/SFIN}ServiceDocType_GFN" minOccurs="0"/&gt;
 *         &lt;element name="ServiceDocID" type="{http://sap.com/xi/SAPSCORE/SFIN}ServiceDocID_GFN" minOccurs="0"/&gt;
 *         &lt;element name="ServiceDocItemID" type="{http://sap.com/xi/SAPSCORE/SFIN}ServiceDocItemID_GFN" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement", propOrder = {
    "customer",
    "customerGroup",
    "customerIndustry",
    "customerCountry",
    "salesDistrict",
    "soldMaterial",
    "soldMaterialGroup",
    "salesOrganization",
    "distributionChannel",
    "division",
    "billToParty",
    "shipToParty",
    "personnelNumber",
    "wbsElement",
    "functionalArea",
    "serviceDocType",
    "serviceDocID",
    "serviceDocItemID"
})
public class JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement {

    @XmlElement(name = "Customer")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String customer;
    @XmlElement(name = "CustomerGroup")
    protected CustomerGroupCode customerGroup;
    @XmlElement(name = "CustomerIndustry")
    protected IndustrialSectorCode customerIndustry;
    @XmlElement(name = "CustomerCountry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String customerCountry;
    @XmlElement(name = "SalesDistrict")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String salesDistrict;
    @XmlElement(name = "SoldMaterial")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String soldMaterial;
    @XmlElement(name = "SoldMaterialGroup")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String soldMaterialGroup;
    @XmlElement(name = "SalesOrganization")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String salesOrganization;
    @XmlElement(name = "DistributionChannel")
    protected DistributionChannelCode distributionChannel;
    @XmlElement(name = "Division")
    protected DivisionCode division;
    @XmlElement(name = "BillToParty")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String billToParty;
    @XmlElement(name = "ShipToParty")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String shipToParty;
    @XmlElement(name = "PersonnelNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String personnelNumber;
    @XmlElement(name = "WBSElement")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String wbsElement;
    @XmlElement(name = "FunctionalArea")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String functionalArea;
    @XmlElement(name = "ServiceDocType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String serviceDocType;
    @XmlElement(name = "ServiceDocID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String serviceDocID;
    @XmlElement(name = "ServiceDocItemID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String serviceDocItemID;

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the customerGroup property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerGroupCode }
     *     
     */
    public CustomerGroupCode getCustomerGroup() {
        return customerGroup;
    }

    /**
     * Sets the value of the customerGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerGroupCode }
     *     
     */
    public void setCustomerGroup(CustomerGroupCode value) {
        this.customerGroup = value;
    }

    /**
     * Gets the value of the customerIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link IndustrialSectorCode }
     *     
     */
    public IndustrialSectorCode getCustomerIndustry() {
        return customerIndustry;
    }

    /**
     * Sets the value of the customerIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndustrialSectorCode }
     *     
     */
    public void setCustomerIndustry(IndustrialSectorCode value) {
        this.customerIndustry = value;
    }

    /**
     * Gets the value of the customerCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCountry() {
        return customerCountry;
    }

    /**
     * Sets the value of the customerCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCountry(String value) {
        this.customerCountry = value;
    }

    /**
     * Gets the value of the salesDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesDistrict() {
        return salesDistrict;
    }

    /**
     * Sets the value of the salesDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesDistrict(String value) {
        this.salesDistrict = value;
    }

    /**
     * Gets the value of the soldMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldMaterial() {
        return soldMaterial;
    }

    /**
     * Sets the value of the soldMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldMaterial(String value) {
        this.soldMaterial = value;
    }

    /**
     * Gets the value of the soldMaterialGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldMaterialGroup() {
        return soldMaterialGroup;
    }

    /**
     * Sets the value of the soldMaterialGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldMaterialGroup(String value) {
        this.soldMaterialGroup = value;
    }

    /**
     * Gets the value of the salesOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrganization() {
        return salesOrganization;
    }

    /**
     * Sets the value of the salesOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrganization(String value) {
        this.salesOrganization = value;
    }

    /**
     * Gets the value of the distributionChannel property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionChannelCode }
     *     
     */
    public DistributionChannelCode getDistributionChannel() {
        return distributionChannel;
    }

    /**
     * Sets the value of the distributionChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionChannelCode }
     *     
     */
    public void setDistributionChannel(DistributionChannelCode value) {
        this.distributionChannel = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link DivisionCode }
     *     
     */
    public DivisionCode getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link DivisionCode }
     *     
     */
    public void setDivision(DivisionCode value) {
        this.division = value;
    }

    /**
     * Gets the value of the billToParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToParty() {
        return billToParty;
    }

    /**
     * Sets the value of the billToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToParty(String value) {
        this.billToParty = value;
    }

    /**
     * Gets the value of the shipToParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToParty() {
        return shipToParty;
    }

    /**
     * Sets the value of the shipToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToParty(String value) {
        this.shipToParty = value;
    }

    /**
     * Gets the value of the personnelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonnelNumber() {
        return personnelNumber;
    }

    /**
     * Sets the value of the personnelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonnelNumber(String value) {
        this.personnelNumber = value;
    }

    /**
     * Gets the value of the wbsElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWBSElement() {
        return wbsElement;
    }

    /**
     * Sets the value of the wbsElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWBSElement(String value) {
        this.wbsElement = value;
    }

    /**
     * Gets the value of the functionalArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalArea() {
        return functionalArea;
    }

    /**
     * Sets the value of the functionalArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalArea(String value) {
        this.functionalArea = value;
    }

    /**
     * Gets the value of the serviceDocType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDocType() {
        return serviceDocType;
    }

    /**
     * Sets the value of the serviceDocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDocType(String value) {
        this.serviceDocType = value;
    }

    /**
     * Gets the value of the serviceDocID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDocID() {
        return serviceDocID;
    }

    /**
     * Sets the value of the serviceDocID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDocID(String value) {
        this.serviceDocID = value;
    }

    /**
     * Gets the value of the serviceDocItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDocItemID() {
        return serviceDocItemID;
    }

    /**
     * Sets the value of the serviceDocItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDocItemID(String value) {
        this.serviceDocItemID = value;
    }

}
