//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//


package com.ap.menabev.soap.journalcreatebinding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryTaxDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryTaxDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TaxCode" type="{http://sap.com/xi/SAPSCORE/SFIN}ProductTaxationCharacteristicsCode"/&gt;
 *         &lt;element name="TaxJurisdiction" type="{http://sap.com/xi/SAPSCORE/SFIN}TaxJurisdictionCode" minOccurs="0"/&gt;
 *         &lt;element name="TaxItemGroup" type="{http://sap.com/xi/SAPSCORE/SFIN}TaxItemGroupID" minOccurs="0"/&gt;
 *         &lt;element name="TaxExpenseAmountInTransacCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="TaxExpenseAmountInCoCodeCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="TaxExpenseAmountInGroupCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryTaxDetails", propOrder = {
    "taxCode",
    "taxJurisdiction",
    "taxItemGroup",
    "taxExpenseAmountInTransacCrcy",
    "taxExpenseAmountInCoCodeCrcy",
    "taxExpenseAmountInGroupCrcy"
})
public class JournalEntryCreateRequestJournalEntryTaxDetails {

    @XmlElement(name = "TaxCode", required = true)
    protected ProductTaxationCharacteristicsCode taxCode;
    @XmlElement(name = "TaxJurisdiction")
    protected TaxJurisdictionCode taxJurisdiction;
    @XmlElement(name = "TaxItemGroup")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String taxItemGroup;
    @XmlElement(name = "TaxExpenseAmountInTransacCrcy")
    protected Amount taxExpenseAmountInTransacCrcy;
    @XmlElement(name = "TaxExpenseAmountInCoCodeCrcy")
    protected Amount taxExpenseAmountInCoCodeCrcy;
    @XmlElement(name = "TaxExpenseAmountInGroupCrcy")
    protected Amount taxExpenseAmountInGroupCrcy;

    /**
     * Gets the value of the taxCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProductTaxationCharacteristicsCode }
     *     
     */
    public ProductTaxationCharacteristicsCode getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductTaxationCharacteristicsCode }
     *     
     */
    public void setTaxCode(ProductTaxationCharacteristicsCode value) {
        this.taxCode = value;
    }

    /**
     * Gets the value of the taxJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link TaxJurisdictionCode }
     *     
     */
    public TaxJurisdictionCode getTaxJurisdiction() {
        return taxJurisdiction;
    }

    /**
     * Sets the value of the taxJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxJurisdictionCode }
     *     
     */
    public void setTaxJurisdiction(TaxJurisdictionCode value) {
        this.taxJurisdiction = value;
    }

    /**
     * Gets the value of the taxItemGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxItemGroup() {
        return taxItemGroup;
    }

    /**
     * Sets the value of the taxItemGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxItemGroup(String value) {
        this.taxItemGroup = value;
    }

    /**
     * Gets the value of the taxExpenseAmountInTransacCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxExpenseAmountInTransacCrcy() {
        return taxExpenseAmountInTransacCrcy;
    }

    /**
     * Sets the value of the taxExpenseAmountInTransacCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxExpenseAmountInTransacCrcy(Amount value) {
        this.taxExpenseAmountInTransacCrcy = value;
    }

    /**
     * Gets the value of the taxExpenseAmountInCoCodeCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxExpenseAmountInCoCodeCrcy() {
        return taxExpenseAmountInCoCodeCrcy;
    }

    /**
     * Sets the value of the taxExpenseAmountInCoCodeCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxExpenseAmountInCoCodeCrcy(Amount value) {
        this.taxExpenseAmountInCoCodeCrcy = value;
    }

    /**
     * Gets the value of the taxExpenseAmountInGroupCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxExpenseAmountInGroupCrcy() {
        return taxExpenseAmountInGroupCrcy;
    }

    /**
     * Sets the value of the taxExpenseAmountInGroupCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxExpenseAmountInGroupCrcy(Amount value) {
        this.taxExpenseAmountInGroupCrcy = value;
    }

}
