//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//


package com.ap.menabev.soap.journalcreatebinding;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryProductTaxItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryProductTaxItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReferenceDocumentItem" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessTransactionDocumentItemID" minOccurs="0"/&gt;
 *         &lt;element name="TaxCode" type="{http://sap.com/xi/SAPSCORE/SFIN}ProductTaxationCharacteristicsCode"/&gt;
 *         &lt;element name="TaxItemClassification" type="{http://sap.com/xi/SAPSCORE/SFIN}TaxItemClassification" minOccurs="0"/&gt;
 *         &lt;element name="ConditionType" type="{http://sap.com/xi/SAPSCORE/SFIN}ConditionType_GFN" minOccurs="0"/&gt;
 *         &lt;element name="TaxJurisdiction" type="{http://sap.com/xi/SAPSCORE/SFIN}TaxJurisdictionCode" minOccurs="0"/&gt;
 *         &lt;element name="TaxJurisdictionLevel" type="{http://sap.com/xi/SAPSCORE/SFIN}TaxJurisdictionLevel" minOccurs="0"/&gt;
 *         &lt;element name="LowestLevelTaxJurisdiction" type="{http://sap.com/xi/SAPSCORE/SFIN}TaxJurisdictionCode" minOccurs="0"/&gt;
 *         &lt;element name="TaxItemGroup" type="{http://sap.com/xi/SAPSCORE/SFIN}TaxItemGroupID" minOccurs="0"/&gt;
 *         &lt;element name="TaxRate" type="{http://sap.com/xi/SAPSCORE/SFIN}Percent" minOccurs="0"/&gt;
 *         &lt;element name="TaxDeterminationDate" type="{http://sap.com/xi/SAPSCORE/SFIN}Date" minOccurs="0"/&gt;
 *         &lt;element name="IsDirectTaxPosting" type="{http://sap.com/xi/SAPSCORE/SFIN}Indicator" minOccurs="0"/&gt;
 *         &lt;element name="AmountInTransactionCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount"/&gt;
 *         &lt;element name="AmountInCompanyCodeCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="AmountInGroupCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="DebitCreditCode" type="{http://sap.com/xi/SAPSCORE/SFIN}DebitCreditCode" minOccurs="0"/&gt;
 *         &lt;element name="TaxBaseAmountInTransCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount"/&gt;
 *         &lt;element name="TaxBaseAmountInCoCodeCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *         &lt;element name="TaxBaseAmountInGroupCrcy" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryProductTaxItem", propOrder = {
    "referenceDocumentItem",
    "taxCode",
    "taxItemClassification",
    "conditionType",
    "taxJurisdiction",
    "taxJurisdictionLevel",
    "lowestLevelTaxJurisdiction",
    "taxItemGroup",
    "taxRate",
    "taxDeterminationDate",
    "isDirectTaxPosting",
    "amountInTransactionCurrency",
    "amountInCompanyCodeCurrency",
    "amountInGroupCurrency",
    "debitCreditCode",
    "taxBaseAmountInTransCrcy",
    "taxBaseAmountInCoCodeCrcy",
    "taxBaseAmountInGroupCrcy"
})
public class JournalEntryCreateRequestJournalEntryProductTaxItem {

    @XmlElement(name = "ReferenceDocumentItem")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String referenceDocumentItem;
    @XmlElement(name = "TaxCode", required = true)
    protected ProductTaxationCharacteristicsCode taxCode;
    @XmlElement(name = "TaxItemClassification")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String taxItemClassification;
    @XmlElement(name = "ConditionType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String conditionType;
    @XmlElement(name = "TaxJurisdiction")
    protected TaxJurisdictionCode taxJurisdiction;
    @XmlElement(name = "TaxJurisdictionLevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String taxJurisdictionLevel;
    @XmlElement(name = "LowestLevelTaxJurisdiction")
    protected TaxJurisdictionCode lowestLevelTaxJurisdiction;
    @XmlElement(name = "TaxItemGroup")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String taxItemGroup;
    @XmlElement(name = "TaxRate")
    protected BigDecimal taxRate;
    @XmlElement(name = "TaxDeterminationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar taxDeterminationDate;
    @XmlElement(name = "IsDirectTaxPosting")
    protected Boolean isDirectTaxPosting;
    @XmlElement(name = "AmountInTransactionCurrency", required = true)
    protected Amount amountInTransactionCurrency;
    @XmlElement(name = "AmountInCompanyCodeCurrency")
    protected Amount amountInCompanyCodeCurrency;
    @XmlElement(name = "AmountInGroupCurrency")
    protected Amount amountInGroupCurrency;
    @XmlElement(name = "DebitCreditCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String debitCreditCode;
    @XmlElement(name = "TaxBaseAmountInTransCrcy", required = true)
    protected Amount taxBaseAmountInTransCrcy;
    @XmlElement(name = "TaxBaseAmountInCoCodeCrcy")
    protected Amount taxBaseAmountInCoCodeCrcy;
    @XmlElement(name = "TaxBaseAmountInGroupCrcy")
    protected Amount taxBaseAmountInGroupCrcy;

    /**
     * Gets the value of the referenceDocumentItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceDocumentItem() {
        return referenceDocumentItem;
    }

    /**
     * Sets the value of the referenceDocumentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceDocumentItem(String value) {
        this.referenceDocumentItem = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProductTaxationCharacteristicsCode }
     *     
     */
    public ProductTaxationCharacteristicsCode getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductTaxationCharacteristicsCode }
     *     
     */
    public void setTaxCode(ProductTaxationCharacteristicsCode value) {
        this.taxCode = value;
    }

    /**
     * Gets the value of the taxItemClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxItemClassification() {
        return taxItemClassification;
    }

    /**
     * Sets the value of the taxItemClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxItemClassification(String value) {
        this.taxItemClassification = value;
    }

    /**
     * Gets the value of the conditionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionType() {
        return conditionType;
    }

    /**
     * Sets the value of the conditionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionType(String value) {
        this.conditionType = value;
    }

    /**
     * Gets the value of the taxJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link TaxJurisdictionCode }
     *     
     */
    public TaxJurisdictionCode getTaxJurisdiction() {
        return taxJurisdiction;
    }

    /**
     * Sets the value of the taxJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxJurisdictionCode }
     *     
     */
    public void setTaxJurisdiction(TaxJurisdictionCode value) {
        this.taxJurisdiction = value;
    }

    /**
     * Gets the value of the taxJurisdictionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxJurisdictionLevel() {
        return taxJurisdictionLevel;
    }

    /**
     * Sets the value of the taxJurisdictionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxJurisdictionLevel(String value) {
        this.taxJurisdictionLevel = value;
    }

    /**
     * Gets the value of the lowestLevelTaxJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link TaxJurisdictionCode }
     *     
     */
    public TaxJurisdictionCode getLowestLevelTaxJurisdiction() {
        return lowestLevelTaxJurisdiction;
    }

    /**
     * Sets the value of the lowestLevelTaxJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxJurisdictionCode }
     *     
     */
    public void setLowestLevelTaxJurisdiction(TaxJurisdictionCode value) {
        this.lowestLevelTaxJurisdiction = value;
    }

    /**
     * Gets the value of the taxItemGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxItemGroup() {
        return taxItemGroup;
    }

    /**
     * Sets the value of the taxItemGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxItemGroup(String value) {
        this.taxItemGroup = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxRate(BigDecimal value) {
        this.taxRate = value;
    }

    /**
     * Gets the value of the taxDeterminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaxDeterminationDate() {
        return taxDeterminationDate;
    }

    /**
     * Sets the value of the taxDeterminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaxDeterminationDate(XMLGregorianCalendar value) {
        this.taxDeterminationDate = value;
    }

    /**
     * Gets the value of the isDirectTaxPosting property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDirectTaxPosting() {
        return isDirectTaxPosting;
    }

    /**
     * Sets the value of the isDirectTaxPosting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDirectTaxPosting(Boolean value) {
        this.isDirectTaxPosting = value;
    }

    /**
     * Gets the value of the amountInTransactionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmountInTransactionCurrency() {
        return amountInTransactionCurrency;
    }

    /**
     * Sets the value of the amountInTransactionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmountInTransactionCurrency(Amount value) {
        this.amountInTransactionCurrency = value;
    }

    /**
     * Gets the value of the amountInCompanyCodeCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmountInCompanyCodeCurrency() {
        return amountInCompanyCodeCurrency;
    }

    /**
     * Sets the value of the amountInCompanyCodeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmountInCompanyCodeCurrency(Amount value) {
        this.amountInCompanyCodeCurrency = value;
    }

    /**
     * Gets the value of the amountInGroupCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmountInGroupCurrency() {
        return amountInGroupCurrency;
    }

    /**
     * Sets the value of the amountInGroupCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmountInGroupCurrency(Amount value) {
        this.amountInGroupCurrency = value;
    }

    /**
     * Gets the value of the debitCreditCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitCreditCode() {
        return debitCreditCode;
    }

    /**
     * Sets the value of the debitCreditCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitCreditCode(String value) {
        this.debitCreditCode = value;
    }

    /**
     * Gets the value of the taxBaseAmountInTransCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxBaseAmountInTransCrcy() {
        return taxBaseAmountInTransCrcy;
    }

    /**
     * Sets the value of the taxBaseAmountInTransCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxBaseAmountInTransCrcy(Amount value) {
        this.taxBaseAmountInTransCrcy = value;
    }

    /**
     * Gets the value of the taxBaseAmountInCoCodeCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxBaseAmountInCoCodeCrcy() {
        return taxBaseAmountInCoCodeCrcy;
    }

    /**
     * Sets the value of the taxBaseAmountInCoCodeCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxBaseAmountInCoCodeCrcy(Amount value) {
        this.taxBaseAmountInCoCodeCrcy = value;
    }

    /**
     * Gets the value of the taxBaseAmountInGroupCrcy property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTaxBaseAmountInGroupCrcy() {
        return taxBaseAmountInGroupCrcy;
    }

    /**
     * Sets the value of the taxBaseAmountInGroupCrcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTaxBaseAmountInGroupCrcy(Amount value) {
        this.taxBaseAmountInGroupCrcy = value;
    }

}
