//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//


package com.ap.menabev.soap.journalcreatebinding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryItemAccountAssignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryItemAccountAssignment"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountAssignmentType" type="{http://sap.com/xi/SAPSCORE/SFIN}AccountAssignmentType" minOccurs="0"/&gt;
 *         &lt;element name="ProfitCenter" type="{http://sap.com/xi/SAPSCORE/SFIN}ProfitCentreID" minOccurs="0"/&gt;
 *         &lt;element name="PartnerProfitCenter" type="{http://sap.com/xi/SAPSCORE/SFIN}ProfitCentreID" minOccurs="0"/&gt;
 *         &lt;element name="Segment" type="{http://sap.com/xi/SAPSCORE/SFIN}SegmentID" minOccurs="0"/&gt;
 *         &lt;element name="PartnerSegment" type="{http://sap.com/xi/SAPSCORE/SFIN}SegmentID" minOccurs="0"/&gt;
 *         &lt;element name="CostCenter" type="{http://sap.com/xi/SAPSCORE/SFIN}CostCentreID" minOccurs="0"/&gt;
 *         &lt;element name="CostCtrActivityType" type="{http://sap.com/xi/SAPSCORE/SFIN}ResourceClassID" minOccurs="0"/&gt;
 *         &lt;element name="WBSElement" type="{http://sap.com/xi/SAPSCORE/SFIN}WBSElement" minOccurs="0"/&gt;
 *         &lt;element name="MasterFixedAsset" type="{http://sap.com/xi/SAPSCORE/SFIN}MasterFixedAssetID" minOccurs="0"/&gt;
 *         &lt;element name="FixedAsset" type="{http://sap.com/xi/SAPSCORE/SFIN}FixedAssetID" minOccurs="0"/&gt;
 *         &lt;element name="SalesOrder" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesOrder" minOccurs="0"/&gt;
 *         &lt;element name="SalesOrderItem" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesOrderItem" minOccurs="0"/&gt;
 *         &lt;element name="FunctionalArea" type="{http://sap.com/xi/SAPSCORE/SFIN}FunctionalArea_GFN" minOccurs="0"/&gt;
 *         &lt;element name="ServiceDocType" type="{http://sap.com/xi/SAPSCORE/SFIN}ServiceDocType_GFN" minOccurs="0"/&gt;
 *         &lt;element name="ServiceDocID" type="{http://sap.com/xi/SAPSCORE/SFIN}ServiceDocID_GFN" minOccurs="0"/&gt;
 *         &lt;element name="ServiceDocItemID" type="{http://sap.com/xi/SAPSCORE/SFIN}ServiceDocItemID_GFN" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryItemAccountAssignment", propOrder = {
    "accountAssignmentType",
    "profitCenter",
    "partnerProfitCenter",
    "segment",
    "partnerSegment",
    "costCenter",
    "costCtrActivityType",
    "wbsElement",
    "masterFixedAsset",
    "fixedAsset",
    "salesOrder",
    "salesOrderItem",
    "functionalArea",
    "serviceDocType",
    "serviceDocID",
    "serviceDocItemID"
})
public class JournalEntryCreateRequestJournalEntryItemAccountAssignment {

    @XmlElement(name = "AccountAssignmentType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String accountAssignmentType;
    @XmlElement(name = "ProfitCenter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String profitCenter;
    @XmlElement(name = "PartnerProfitCenter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String partnerProfitCenter;
    @XmlElement(name = "Segment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String segment;
    @XmlElement(name = "PartnerSegment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String partnerSegment;
    @XmlElement(name = "CostCenter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String costCenter;
    @XmlElement(name = "CostCtrActivityType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String costCtrActivityType;
    @XmlElement(name = "WBSElement")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String wbsElement;
    @XmlElement(name = "MasterFixedAsset")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String masterFixedAsset;
    @XmlElement(name = "FixedAsset")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String fixedAsset;
    @XmlElement(name = "SalesOrder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String salesOrder;
    @XmlElement(name = "SalesOrderItem")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String salesOrderItem;
    @XmlElement(name = "FunctionalArea")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String functionalArea;
    @XmlElement(name = "ServiceDocType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String serviceDocType;
    @XmlElement(name = "ServiceDocID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String serviceDocID;
    @XmlElement(name = "ServiceDocItemID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String serviceDocItemID;

    /**
     * Gets the value of the accountAssignmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountAssignmentType() {
        return accountAssignmentType;
    }

    /**
     * Sets the value of the accountAssignmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountAssignmentType(String value) {
        this.accountAssignmentType = value;
    }

    /**
     * Gets the value of the profitCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitCenter() {
        return profitCenter;
    }

    /**
     * Sets the value of the profitCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitCenter(String value) {
        this.profitCenter = value;
    }

    /**
     * Gets the value of the partnerProfitCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerProfitCenter() {
        return partnerProfitCenter;
    }

    /**
     * Sets the value of the partnerProfitCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerProfitCenter(String value) {
        this.partnerProfitCenter = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment(String value) {
        this.segment = value;
    }

    /**
     * Gets the value of the partnerSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerSegment() {
        return partnerSegment;
    }

    /**
     * Sets the value of the partnerSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerSegment(String value) {
        this.partnerSegment = value;
    }

    /**
     * Gets the value of the costCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenter() {
        return costCenter;
    }

    /**
     * Sets the value of the costCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenter(String value) {
        this.costCenter = value;
    }

    /**
     * Gets the value of the costCtrActivityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCtrActivityType() {
        return costCtrActivityType;
    }

    /**
     * Sets the value of the costCtrActivityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCtrActivityType(String value) {
        this.costCtrActivityType = value;
    }

    /**
     * Gets the value of the wbsElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWBSElement() {
        return wbsElement;
    }

    /**
     * Sets the value of the wbsElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWBSElement(String value) {
        this.wbsElement = value;
    }

    /**
     * Gets the value of the masterFixedAsset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterFixedAsset() {
        return masterFixedAsset;
    }

    /**
     * Sets the value of the masterFixedAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterFixedAsset(String value) {
        this.masterFixedAsset = value;
    }

    /**
     * Gets the value of the fixedAsset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedAsset() {
        return fixedAsset;
    }

    /**
     * Sets the value of the fixedAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedAsset(String value) {
        this.fixedAsset = value;
    }

    /**
     * Gets the value of the salesOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrder() {
        return salesOrder;
    }

    /**
     * Sets the value of the salesOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrder(String value) {
        this.salesOrder = value;
    }

    /**
     * Gets the value of the salesOrderItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrderItem() {
        return salesOrderItem;
    }

    /**
     * Sets the value of the salesOrderItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrderItem(String value) {
        this.salesOrderItem = value;
    }

    /**
     * Gets the value of the functionalArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalArea() {
        return functionalArea;
    }

    /**
     * Sets the value of the functionalArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalArea(String value) {
        this.functionalArea = value;
    }

    /**
     * Gets the value of the serviceDocType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDocType() {
        return serviceDocType;
    }

    /**
     * Sets the value of the serviceDocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDocType(String value) {
        this.serviceDocType = value;
    }

    /**
     * Gets the value of the serviceDocID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDocID() {
        return serviceDocID;
    }

    /**
     * Sets the value of the serviceDocID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDocID(String value) {
        this.serviceDocID = value;
    }

    /**
     * Gets the value of the serviceDocItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDocItemID() {
        return serviceDocItemID;
    }

    /**
     * Sets the value of the serviceDocItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDocItemID(String value) {
        this.serviceDocItemID = value;
    }

}
