//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 01:12:35 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sap.com/xi/SAPSCORE/SFIN")
package com.ap.menabev.soap.journalcreatebinding;
